spring.application.name=movie-theater-backend

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.access-token-expiration=${APP_JWT_ACCESS_EXPIRATION}
app.jwt.refresh-token-expiration=${APP_JWT_REFRESH_EXPIRATION}
app.google.client-id=${GOOGLE_WEB_CLIENT_ID}

# Seed - Admin
app.auth.seed.admin-email=${APP_SEED_ADMIN_EMAIL}
app.auth.seed.admin-password=${APP_SEED_ADMIN_PASSWORD}
app.auth.seed.admin-full-name=${APP_SEED_ADMIN_FULL_NAME}

# Seed - Staff
app.auth.seed.staff-email=${APP_SEED_STAFF_EMAIL}
app.auth.seed.staff-password=${APP_SEED_STAFF_PASSWORD}
app.auth.seed.staff-full-name=${APP_SEED_STAFF_FULL_NAME}

# Seed - Customer
app.auth.seed.customer-email=${APP_SEED_CUSTOMER_EMAIL}
app.auth.seed.customer-password=${APP_SEED_CUSTOMER_PASSWORD}
app.auth.seed.customer-full-name=${APP_SEED_CUSTOMER_FULL_NAME}

# Mail Configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_SMTP_STARTTLS_REQUIRED}

spring.mail.properties.mail.smtp.connectiontimeout=${MAIL_SMTP_CONNECTION_TIMEOUT}
spring.mail.properties.mail.smtp.timeout=${MAIL_SMTP_TIMEOUT}
spring.mail.properties.mail.smtp.writetimeout=${MAIL_SMTP_WRITE_TIMEOUT}

# Frontend Config
app.frontend-url=${APP_FRONTEND_URL}
# Cloudinary Config
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Showtime Config
app.showtime.auto-slide-enabled=true

