export const SYSTEM_CONFIG_STORAGE_KEY = 'lorafilm_system_config';

export const DEFAULT_ROOM_TYPES = [
  { value: 'STANDARD', label: 'Standard 2D/3D', enabled: true },
  { value: 'IMAX', label: 'IMAX Laser', enabled: true },
  { value: 'VIP', label: 'VIP Gold Class', enabled: true },
  { value: 'DOLBY_ATMOS', label: 'Dolby Atmos', enabled: true },
  { value: 'FOUR_DX', label: '4DX Motion Cinema', enabled: true },
];

export const DEFAULT_SCREENING_FORMATS = [
  { value: '2D', label: '2D Phụ đề / Lồng tiếng', enabled: true },
  { value: '3D', label: '3D', enabled: true },
  { value: 'IMAX', label: 'IMAX Laser', enabled: true },
  { value: '4DX', label: '4DX Motion', enabled: true },
  { value: 'DOLBY_ATMOS', label: 'Dolby Atmos', enabled: true },
  { value: 'SCREENX', label: 'ScreenX', enabled: true },
];

export const DEFAULT_SYSTEM_CONFIG = {
  startTime: '08:00',
  endTime: '23:30',
  intervalMinutes: 15,
  trailerBuffer: 10,
  slotStepMinutes: 30,
  gridAlignMinutes: 15,
  fairnessPenalty: 25,
  sameMovieGapMinutes: 30,
  defaultRating: 8,
  defaultDurationMinutes: 120,
  weekendScore: 10,
  weekdayScore: 0,
  includeFridayAsWeekend: true,
  goldenHourPeakStart: '18:00',
  goldenHourPeakEnd: '22:30',
  goldenHourPeakScore: 15,
  goldenHourNearStart1: '12:00',
  goldenHourNearEnd1: '18:00',
  goldenHourNearStart2: '22:30',
  goldenHourNearEnd2: '23:59',
  goldenHourNearScore: 8,
  genreTierHot: 10,
  genreTierMid: 7,
  genreTierBase: 4,
  genreHotKeywords: ['hành động', 'viễn tưởng', 'hoạt hình'],
  genreMidKeywords: ['phiêu lưu', 'kịch tính', 'tình cảm'],
  previewScoreHigh: 25,
  previewScoreMid: 15,
  goldenHourWeight: 1.2,
  weekendWeight: 1.5,
  ratingWeight: 1.0,
  genreWeight: 1.1,
  basePrice: 60000,
  vipPrice: 90000,
  couplePrice: 120000,
  onlineStreamingPrice: 45000,
  seatLockMinutes: 5,
  maxSeatsPerBooking: 8,
  onlineWatchLockMultiplier: 2,
  onlineCountdownEnabled: true,
  onlineCountdownWarningMinutes: 10,
  pointsEarningRatio: 5,
  pointsToCashValue: 1000,
  sessionTimeoutHours: 24,
  cancellationCutoffMinutes: 60,
  cancellationFeePercent: 10,
  customerRefundEnabled: true,
  fullRefundOnShowtimeCancel: true,
  refundManualApprovalRequired: true,
  roomTypes: DEFAULT_ROOM_TYPES,
  screeningFormats: DEFAULT_SCREENING_FORMATS,
  reviewBannedWords: [],
};
