name: Deploy to VPS

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Di chuyển vào thư mục backend trên VPS
            cd ~/NasaFilm/movie-theater-be
            
            # Chạy file bash script của bạn (file này đã có sẵn lệnh pull code và docker compose)
            bash deploy.sh
